events {}

http {


    log_format upstreamlog
    '$remote_addr - [$time_local] '
    '"$request" '
    'status=$status '
    'upstream=$upstream_addr';


    access_log /var/log/nginx/access.log upstreamlog;


    upstream backend {

        server api1:3000;
        server api2:3000;

    }


    server {

        listen 80;


        location / {

            proxy_pass http://backend;

        }

    }

}