name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint

  test-unit:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env
        run: |
          echo "NODE_ENV=test" > .env
          echo "JWT_SECRET" > .env


      - name: Run unit tests
        run: npm run test:unit

  test-integration-and-e2e:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin

    env:
      NODE_ENV: test
      MONGO_URI: mongodb://admin:admin@localhost:27017/barDaFiloTest?authSource=admin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env
        run: |
          echo "NODE_ENV=test" > .env
          echo "MONGO_URI=mongodb://admin:admin@localhost:27017/barDaFiloTest?authSource=admin" >> .env

      - name: Wait MongoDB
        run: sleep 10

      - name: Run integration tests
        run: npm run test:int-concurrency1

      - name: Run e2e tests
        run: npm run test:e2e-concurrency1

  build:
    needs:
        - lint
        - test-unit
        - test-integration-and-e2e

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build 

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: imageApi
          path: main
 
  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

    

    